/*
 * Copyright (c) 2026 Ivan Kniazkov
 */

package com.kniazkov.webserver.impl;

import com.kniazkov.webserver.HttpVersion;
import com.kniazkov.webserver.Response;
import com.kniazkov.webserver.ServerException;

import java.io.ByteArrayOutputStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Serializes HTTP responses.
 */
final class ResponseSerializer {

    /**
     * The carriage return and line feed sequence.
     */
    private static final byte[] CRLF = {
        '\r', '\n'
    };

    /**
     * Prevents instantiation.
     */
    private ResponseSerializer() {
    }

    /**
     * Serializes an HTTP response.
     * <p>
     * Framing, representation metadata, and connection headers supplied by
     * the response are ignored. Their values are generated by the server.
     *
     * @param response
     *     the response.
     * @param version
     *     the HTTP version.
     * @param keepAlive
     *     whether the connection remains open after the response.
     * @return
     *     the complete serialized HTTP response.
     * @throws ServerException
     *     if an application-supplied response header is invalid.
     */
    static byte[] serialize(
        final Response response,
        final HttpVersion version,
        final boolean keepAlive
    ) throws ServerException {
        final byte[] data = response.getData();
        final ByteArrayOutputStream output = new ByteArrayOutputStream();

        write(
            output,
            version.toString()
                + " "
                + response.getStatus().getCode()
                + " "
                + response.getStatus().getReason()
        );
        writeCrlf(output);

        for (
            Map.Entry<String, List<String>> entry
            : response.getHeaders().entrySet()
        ) {
            final String name = entry.getKey();

            if (ResponseHeaderValidator.isServerManaged(name)) {
                continue;
            }

            for (String value : entry.getValue()) {
                writeHeader(
                    output,
                    ResponseHeaderValidator.validate(
                        name,
                        value
                    ),
                    value
                );
            }
        }

        if (!keepAlive) {
            writeHeader(output, "Connection", "close");
        } else if (version == HttpVersion.HTTP_1_0) {
            writeHeader(output, "Connection", "keep-alive");
        }

        if (response.getStatus().allowsBody()) {
            String contentType = response
                .getContentType()
                .getValue();
            final Optional<Charset> charset = response.getCharset();

            if (charset.isPresent()) {
                contentType += "; charset="
                    + charset.orElseThrow().name();
            }

            writeHeader(
                output,
                "Content-Type",
                contentType
            );

            writeHeader(
                output,
                "Content-Length",
                Integer.toString(data.length)
            );
        }

        writeCrlf(output);

        if (response.getStatus().allowsBody()) {
            output.writeBytes(data);
        }

        return output.toByteArray();
    }

    /**
     * Writes one HTTP header.
     *
     * @param output
     *     the output stream.
     * @param name
     *     the header name.
     * @param value
     *     the header value.
     */
    private static void writeHeader(
        final ByteArrayOutputStream output,
        final String name,
        final String value
    ) {
        write(output, name);
        write(output, ": ");
        write(output, value);
        writeCrlf(output);
    }

    /**
     * Writes HTTP header text using its single-byte wire representation.
     *
     * @param output
     *     the output stream.
     * @param value
     *     the text.
     */
    private static void write(
        final ByteArrayOutputStream output,
        final String value
    ) {
        output.writeBytes(
            value.getBytes(StandardCharsets.ISO_8859_1)
        );
    }

    /**
     * Writes CRLF.
     *
     * @param output
     *     the output stream.
     */
    private static void writeCrlf(
        final ByteArrayOutputStream output
    ) {
        output.writeBytes(CRLF);
    }
}
