/*
 * Copyright (c) 2024 Ivan Kniazkov
 */
package com.kniazkov.webserver;

import java.util.Map;
import java.util.TreeMap;

/**
 * Request received from a client and then parsed.
 */
public final class Request {
    /**
     * The address entered in the address line, or generated by an HTTP request.<br/>
     * Examples:
     * <ul>
     *     <li>{@code /} - root, i.e. the address line looks like: {@code http://domain/}</li>
     *     <li>{@code /filename.html} - a specific file, e.g. {@code http://domain/filename.html}</li>
     *     <li>{@code /?key=value} - form data passed by GET method</li>
     *     <li>{@code /filename.html?key=value} - both file name and GET form data</li>
     * </ul>
     */
    public String address = "";

    /**
     * HTTP version string, such as {@code HTTP/1.0} or {@code HTTP/1.1}.
     */
    public String httpVersion = "HTTP/1.0";

    /**
     * HTTP request method processed by this server.
     */
    public Method method = Method.UNKNOWN;

    /**
     * All HTTP headers received in the request.<br/>
     * Keys are case-insensitive, values are raw strings without trimming.
     */
    public Map<String, String> headers = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);

    /**
     * Parsed web form data (query string parameters or URL-encoded body).
     */
    public Map<String, String> formData = new TreeMap<>();

    /**
     * Parsed web form data containing transferred files using POST method
     * with <code>multipart/form-data</code>.
     */
    public Map<String, FileDescriptor> files = new TreeMap<>();

    /**
     * Indicates whether the client requested to close the connection
     * after this request. Typically derived from the {@code Connection}
     * header in HTTP/1.1.
     */
    public boolean closeConnection = false;

    /**
     * Path part of the request URI (everything before '?').
     * For example, {@code /api/data} in {@code /api/data?x=1}.
     */
    public String path = "";

    /**
     * Query part of the request URI (everything after '?').
     * For example, {@code x=1&y=2} in {@code /api/data?x=1&y=2}.
     */
    public String query = "";
}
