/*
 * Copyright (c) 2026 Ivan Kniazkov
 */

package com.kniazkov.webserver;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Converts HTTP response objects into complete HTTP messages.
 */
public final class ResponseSerializer {

    /**
     * The HTTP line separator.
     */
    private static final String LINE_SEPARATOR = "\r\n";

    /**
     * Prevents instantiation of this utility class.
     */
    private ResponseSerializer() {
    }

    /**
     * Serializes a response using the HTTP version of the specified request.
     *
     * @param request
     *     the request associated with the response.
     * @param response
     *     the response to serialize.
     * @return
     *     the complete serialized HTTP message.
     * @throws NullPointerException
     *     if the request or response is {@code null}.
     */
    public static byte[] serialize(
        final Request request,
        final Response response
    ) {
        Objects.requireNonNull(request, "Request must not be null.");

        return serialize(
            request.getHeader().getVersion(),
            response
        );
    }

    /**
     * Serializes a response using the specified HTTP version.
     *
     * @param version
     *     the HTTP protocol version.
     * @param response
     *     the response to serialize.
     * @return
     *     the complete serialized HTTP message.
     * @throws NullPointerException
     *     if the version or response is {@code null}.
     */
    public static byte[] serialize(
        final HttpVersion version,
        final Response response
    ) {
        Objects.requireNonNull(
            version,
            "HTTP version must not be null."
        );
        Objects.requireNonNull(
            response,
            "Response must not be null."
        );

        final byte[] data = response.getData();
        final StringBuilder header = new StringBuilder();

        appendStatusLine(header, version, response.getStatus());
        appendGeneratedHeaders(header, response, data.length);
        appendAdditionalHeaders(header, response.getHeaders());
        header.append(LINE_SEPARATOR);

        final byte[] headerData = header.toString().getBytes(
            StandardCharsets.ISO_8859_1
        );

        final ByteArrayOutputStream output = new ByteArrayOutputStream(
            headerData.length + data.length
        );
        output.writeBytes(headerData);
        output.writeBytes(data);

        return output.toByteArray();
    }

    /**
     * Appends the HTTP status line.
     *
     * @param target
     *     the destination string builder.
     * @param version
     *     the HTTP protocol version.
     * @param status
     *     the HTTP response status.
     */
    private static void appendStatusLine(
        final StringBuilder target,
        final HttpVersion version,
        final HttpStatus status
    ) {
        target
            .append(version)
            .append(' ')
            .append(status.getCode())
            .append(' ')
            .append(status.getReason())
            .append(LINE_SEPARATOR);
    }

    /**
     * Appends header fields generated by the serializer.
     *
     * @param target
     *     the destination string builder.
     * @param response
     *     the response being serialized.
     * @param contentLength
     *     the response body length.
     */
    private static void appendGeneratedHeaders(
        final StringBuilder target,
        final Response response,
        final int contentLength
    ) {
        target
            .append("Content-Type: ")
            .append(response.getContentType())
            .append(LINE_SEPARATOR)
            .append("Content-Length: ")
            .append(contentLength)
            .append(LINE_SEPARATOR);
    }

    /**
     * Appends additional response header fields.
     * <p>
     * User-supplied {@code Content-Type} and {@code Content-Length} fields are
     * ignored because these fields are generated by the serializer.
     *
     * @param target
     *     the destination string builder.
     * @param headers
     *     the additional response header fields.
     */
    private static void appendAdditionalHeaders(
        final StringBuilder target,
        final Map<String, List<String>> headers
    ) {
        for (Map.Entry<String, List<String>> entry : headers.entrySet()) {
            final String name = entry.getKey();

            if (isGeneratedHeader(name)) {
                continue;
            }

            for (String value : entry.getValue()) {
                target
                    .append(name)
                    .append(": ")
                    .append(value)
                    .append(LINE_SEPARATOR);
            }
        }
    }

    /**
     * Returns whether the specified header is generated by the serializer.
     *
     * @param name
     *     the header field name.
     * @return
     *     {@code true} if the header is generated automatically.
     */
    private static boolean isGeneratedHeader(final String name) {
        return "Content-Type".equalsIgnoreCase(name)
            || "Content-Length".equalsIgnoreCase(name);
    }
}
